### ISSUE TITLE
Uncaught Invariant Violation: ReactDOM.render(): Invalid component element.

### ISSUE THREAD

**Issue by jeffgran** [netguru/rwr-react_router#7]
It seems there is a race condition when initializing the router. If it runs before the document is ready, `ReactDOM` cannot find the element it wants to render the router to. We worked around this by using this code:

    document.addEventListener('DOMContentLoaded', function() {
      ReactDOM.render(...)
    }

instead of using the RWR integration. Maybe this should be part of the RWR initialization process?

**Comment by mxaly** [comment]
hi @jeffgran 
Can you pls share a bit more context here? 
Are you using `react_router` rails helper or you are trying to render it js-side with RWR integration?

**Comment by jeffgran** [comment]
Yeah, sorry for being vague.

Yes, I was using `<%= react_router('App') %>` in my rails view. 

In my `index.js` I had `function App(props) {  return (<Router ... />); }`

This was in a fresh, empty rails app, with nothing in the layout besides the standard empty `<body>` tag.

Let me know if you need any more info.

**Comment by mxaly** [comment]
Thanks! Trying to reproduce this one. In the mean time you can try to compare your solution with example from our specs: 
[router](https://github.com/netguru/rwr-react_router/blob/master/spec/rails4_dummy_app/app/react/routers/with-props.jsx) [index](https://github.com/netguru/rwr-react_router/blob/master/spec/rails4_dummy_app/app/react/index.js) and [view](https://github.com/netguru/rwr-react_router/blob/master/spec/rails4_dummy_app/app/views/pages/with_props.erb)

**Comment by mxaly** [comment]
Just realized, that there is no info about registering react-router integration in RWR  :( 
Can you check it adding this will solve your problem? 
https://github.com/netguru/rwr-react_router/blob/master/spec/rails4_dummy_app/app/react/index.js#L5

**Comment by jeffgran** [comment]
Yep, that fixed it! Thanks.
